# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "Women Techmakers Rio 2015"
email: "nos@wtmrio.com.br"
description: "Women Techmakers Rio"
baseurl: ""
url: "http://wtmrio.com.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-54291559-1"
googleAnalyticsSiteUrl: "wtmrio.com.br"

# Organizer Info
organizerName: "Women Techmakers Rio"
organizerAlternateName: "Women Techmakers Rio"
organizerDescription: "Comunidades abertas de geeks voluntários que criam projetos incríveis e compartilham de forma apaixonada suas experiências com as tecnologias do Google."
organizerEmail: "nos@wtmrio.com.br"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://wtmrio.com.br/"

# Head
metaKeywords: "evento, gdg, google, programação, design, android, mobile, web, desenvolvedores, rio, riodejaneiro, brasil, brazil, gdgrj, gdgrio, pyladies, djangogirls, horaextra"
twitterAccount: "@WTMRio"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/11SMKmGfSmkQ0hBA06g-WeZnGNcU5-Sy7IRA9FM_bbP8/viewform"
# c4sponsorsUrl: "/assets/devfest-midiakit-final.pdf"
# c4sponsorsUrlEn: "/assets/devfest-midiakit-final-en.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 # - {permalink: "/schedule/", text: "Agenda"}
 # - {permalink: "/speakers/", text: "Palestrantes"}
 - {permalink: "/team/", text: "Time"}
 - {permalink: "/logistics/", text: "Logística"}
 # - {link: "https://developers.google.com", text: "Desenvolvedores"}

 # bottomNavigationLinks:
 # - {link: "http://wtmrio.eventbrite.com/?aff=site", text: "Inscreva-se"}
 # - {link: "https://docs.google.com/forms/d/1egw-Kjo86PivWiu6yUwUW0tyY9jkNTiwU3nFzWK24Fk/viewform", text: "Seja um palestrante"}
 # - {link: "https://docs.google.com/forms/d/1dVn4WmqAFiQm-4KKHMoUH5UgX-SWaWdLSATexr1lMyQ/viewform", text: "Seja um voluntário"}
 # rightNavigationButtons:
 #- {link: "https://docs.google.com/forms/d/1egw-Kjo86PivWiu6yUwUW0tyY9jkNTiwU3nFzWK24Fk/viewform", text: "Seja um palestrante"}






# Hero Block
heroTitle: "Women Techmakers <typeout> 2015"
eventDate: "18 de Julho de 2015"
typeoutTextValues: '"Rio", "Carioca", "RJ", "Rio de Janeiro"'
heroButtons:
- {url: "https://docs.google.com/forms/d/11SMKmGfSmkQ0hBA06g-WeZnGNcU5-Sy7IRA9FM_bbP8/viewform", text: "Participe"}
 # - {url: "http://wtmrio.eventbrite.com/?aff=site", text: "Faça sua inscrição!"}




# About Block
aboutTitle: "Sobre o Women Techmakers Rio"
aboutBlock:
 - {title: "Conferência", image: "conference.jpg", text: "Apoiar mulheres na tecnologia através do exemplo." }
 - {title: "Palestras", image: "workshop.jpg", text: "Googlers e membros da comunidade falando sobre tecnologia, design e empreendedorismo." }
 - {title: "Discussões", image: "hackathon.jpg", text: "Como reduzir a diferença de gêneros na ciência, tecnologia, engenharia e matemática? No palco discussões com líderes e especialistas." }




# Statistic Block
# statisticBlock:
 # - {count: "450", specialCharacter: "+", info: "participantes", detail: "de todo lugar"}
 # - {count: "25", specialCharacter: "+", info: "palestrantes", detail: "e especialistas de tecnologia"}
 # - {count: "8", specialCharacter: "", info: "horas", detail: "de pura tecnologia"}
 # - {count: "3", specialCharacter: "", info: "trilhas paralelas", detail: "e muitas novidades"}




# Strategy Block
strategyTitle: "No que acreditamos"
strategyBlock:
  - {title: "Missão", text: "Chamar atenção para questões de igualdade de gênero e diversidade para as áreas do STEM (CTEM em português, acrônimo para ciência, tecnologia, engenharia e matemática) através do poder do exemplo. Criar um ambiente aberto onde os desafios podem ser entendidos e superados. <br /><br />Nossas ações seguirão essa missão, isto é o que nossos eventos devem oferecer e é assim que nós julgaremos nossas atividades para ver se elas foram bem sucedidas ou não. <br /><br />Não é só sobre o número de participantes, embora um alcance maior seja benéfico, é sobre transmitir a mensagem certa para as pessoas certas, sobre fortalecimento dos aliados e desenvolvimento de estratégias de melhoria. <br /><br />Acreditamos que a mudança deve partir de todos, independente do gênero. Nossos eventos devem continuar abertos aos participantes de qualquer gênero e pessoas sem gênero."}
  - {title: "Valores", text: "Respeito, Confiança, Justiça, Abraçar Diferenças, Compartilhar, Apoiar, Aperfeiçoar <br /><br />Nossos valores são o que acreditamos que todos deveriam se basear. Eles também são o que usamos como referência de nossas ações. Nós queremos que todos sejam respeitados como pessoas, tendo confiança e sendo tratados de forma justa, queremos igualdade de valor enquanto entendemos as diferenças - acreditamos que o uso de diferentes formas de pensar unidas nos proporcionam uma qualidade melhor. Nós queremos que informações sejam compartilhadas e colegas apoiados, tudo com o propósito da melhoria contínua."}
  - {title: "Visão", text: "Igualdade e diversidade nas áreas do STEM independe do gênero. <br/><br/>Este é o mundo que sonhamos, um mundo onde mulheres não têm que dar 120% para serem levadas à sério, um mundo onde homens e mulheres trabalham juntos explorando a ciência, desenvolvendo tecnologia, construindo a engenharia e criando uma base matemática, um mundo onde a escolha de uma área específica de estudo não é uma questão de gênero. <br/><br/>Muitas vezes podemos falar sobre homens e mulheres mas estamos cientes sobre a grande variação existente, as visões específicas de pessoas cis- e transgênero, os aspectos dos não-binários e das pessoas sem gênero. A escolha de carreira ou estudo no STEM deve ser independente da identidade de gênero."}




# Latest News Block
# latestNewsTitle: "Últimas Notícias"

# Rockstar Speakers Block
rockstarSpeakersCount: 0
# rockstarSpeakersTitle: "Palestrantes feras"
# rockstarSpeakersButtonText: "conheça todos os palestrantes"




#https://goo.gl/maps/v9WZy (restaurantes próximos)

# Location Block
locationBlockTitle: "Local"
eventLocationName: "Ideais Tecnologia"
eventLocationLink: "http://www.ideais.com.br/"
eventStreetAddress: "Rua da Quitanda, 86 - 9º andar - Centro"
eventAddressLocality: "Rio de Janeiro"
eventAddressLocalityRegion: "RJ"
eventPostalCode: "20091-005"
eventAddressCountry: "Brasil"
eventStartTime: "2015-06-27T8:00"
eventDoorTime: "09:00"
eventEndTime: "2015-06-27T18:00"
eventPlaceCoordinates: "-22.9027329,-43.1773005"
mapCenterCoordinates: "-22.9027329,-43.1773005"
mapMobileCenterCoordinates: "-22.9027329,-43.1773005"




# Venue Block
# venueBlockTitle: "Venue"
# venueTitle: "Kinopalace Cinema"
# venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]






# # Tweets Feed Block
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "devfest"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Seja um patrocinador"
partnersC4sponsorsButtonEn: "Become a sponsor"

# # Organizers Block
# organizersTitle: "Organizers"

# # Subscribe Block
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"


# Buy Tickets Block
# ticketsTitle: "Inscreva-se"

# ticketsOffers:
#  -
#   name: "Believe in the Force"
#   price: "105"
#   priceCurrency: "R$"
#   buyButtonLink: "http://wtmrio.eventbrite.com/?aff=site"
#   buyButtonText: "Comprar"
#   # additionalInfo: "Preço válido até 15/10/2014"
#   validFrom: "2014-10-01T00:00"
#   validThrough: "2014-10-15T23:59"
#   soldOut: true
#   soldOutText: "Esgotado"
#  -
#   name: "Become a Jedi"
#   price: "120"
#   priceCurrency: "R$"
#   buyButtonLink: "https://wtmrio.eventbrite.com/"
#   buyButtonText: "Comprar"
#   ticketContentList: ["Desconto válido até 15/11/2014"]
#   validFrom: "2014-10-16T00:00"
#   validThrough: "2014-10-31T23:59"
#   soldOut: true
#   soldOutText: "Esgotado"
#  -
#   name: "The dark side"
#   price: "200"
#   priceCurrency: "R$"
#   buyButtonLink: "http://wtmrio.eventbrite.com/?aff=site"
#   buyButtonText: "Compre agora!"
#   validFrom: "2014-11-01T00:00"
#   validThrough: "2014-11-18T23:59"
#   soldOut: true
#   soldOutText: "Esgotado"



# Footer
socialLinks:
 - {link: "https://plus.google.com/communities/103235871339020087970", icon: "google-plus"}
 - {link: "https://www.facebook.com/wtmRio", icon: "facebook"}
 - {link: "https://twitter.com/WTMRio", icon: "twitter"}

footerBlocks:
 -
  title: "Grupos"
  links:
   - {link: "https://developers.google.com/groups/chapter/104464728601797437216/", text: "GDG-RJ"}
   - {link: "http://brasil.pyladies.com/", text: "Pyladies Brasil"}
   - {link: "http://djangogirls.org/niteroi/", text: "Django Girls Brasil"}
   # - {link: "http://www.gdgsorocaba.org", text: "GDG-Sorocaba"}
 -
  title: "Meetups"
  links:
   - {link: "http://www.meetup.com/Hora-Extra-Barra/", text: "Horaextra Barra"}
   # - {link: "http://www.meetup.com/GDG-ABC/", text: "Meetups GDG-ABC"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:nos@wtmrio.com.br", text: "nos@wtmrio.com.br"}
#   - {link: "tel:+5511983370955", text: "+55 11 983-370-955"}





# Blog
# blogTitle: "Últimas novidades"
# blogCommentsEnabled: true
# discusShortName: "wtmrio"



# Speakers List Block
showSessions: false
thumbnailsFolder: /img/speakers/



# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "Os serviços do Google se tornam sinônimos de coisas simples na internet. O número de inovações tecnológicas e da insústria de TI em que o Google está criando novos produtos é enorme. É difícil conhecer todas. É por isso que as pessoas começaram a se reunir em pequenos grupos locais e compartilhar suas experiências. Mais tarde, os seguintes grupos foram chamados de Google Developer Groups. GDGs podem assumir muitas formas -- desde algumas pessoas se reunindo para assistir alguns vídeos até grande encontros com demonstrações, palestras técnicas, hackathons e conferências."
teamOrganizers: "Organizadores"
# teamProgramCommittee: "Comitê"
teamThumbnailsFolder: /img/team/


# Logistics Find Way Block
findWayTitle: "Como chegar aqui"
logisticsMapCenterCoordinates: "-22.9027329,-43.1773005"
logisticsMapMobileCenterCoordinates: "-22.9027329,-43.1773005"

findWayDistance: "Distância"
findWayToEvent: "para o WTM"
findWayPlaceholder: "Sua localização"
findWayDriving: "CARRO"
findWayWalking: "ANDANDO"
findWayBicycling: "BICICLETA"
findWayTransit: "ÔNIBUS"





# Logistics Direction Details Block
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
